language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update --dev --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --access-token="9f7c1f77406519d4acf36b843e6838dee2a5a6ae51c86fd7e96b7ea33897f513" --format=php-clover ./build/logs/clover.xml
